name=Soldered u-blox GPS GNSS
version=1.0.0
author=Soldered
maintainer=Soldered <hello@soldered.com>
sentence=Library for I2C, Serial and SPI communication with u-blox GPS/GNSS modules
paragraph=Library for the Soldered u-blox GPS/GNSS breakout boards. Supports I2C, UART and SPI communication using both NMEA and UBX protocols. Compatible with u-blox modules such as NEO-M9N, ZED-F9P and many others.
category=Sensors
url=https://www.soldered.com/
repository=https://github.com/SolderedElectronics/Soldered-u-blox-GPS-GNSS-Arduino-Library
architectures=*
includes=Soldered-GNSS.h
